package archive

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/segmentio/parquet-go"
)

// fileState tracks a file being unpacked
type fileState struct {
	meta   *FileRecord
	handle *os.File
	chunks map[int64][]byte // pending out-of-order chunks
}

func Unpack(ctx context.Context, opts UnpackOptions) error {
	if opts.Workers <= 0 {
		opts.Workers = 1
	}
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	return unpackCombined(ctx, opts, opts.ParquetFile)
}

func unpackCombined(ctx context.Context, opts UnpackOptions, dataPath string) error {
	f, err := os.Open(dataPath)
	if err != nil {
		return fmt.Errorf("open parquet: %w", err)
	}
	defer f.Close()

	// Safely create reader, catching panics from invalid parquet files
	var reader *parquet.Reader
	func() {
		defer func() {
			if r := recover(); r != nil {
				reader = nil // Signal invalid parquet
			}
		}()
		reader = parquet.NewReader(f)
	}()

	if reader == nil {
		return fmt.Errorf("invalid or incompatible parquet file\nThis file was not created by modelvault. Ensure you're using a parquet file generated by 'modelvault pack'")
	}

	// Track open files for direct writing
	openFiles := make(map[string]*fileState)
	defer func() {
		for _, state := range openFiles {
			state.handle.Close()
		}
	}()

	recordCount := 0
	firstRecordRead := false

	// Stream records and buffer chunks
	for {
		var record FileRecord
		if err := reader.Read(&record); err != nil {
			if err.Error() != "EOF" {
				if !firstRecordRead {
					return fmt.Errorf("invalid or incompatible parquet file: %w\nThis file was not created by modelvault. Ensure you're using a parquet file generated by 'modelvault pack'", err)
				}
				return fmt.Errorf("read record %d: %w", recordCount, err)
			}
			break
		}

		firstRecordRead = true

		// Lazy init file on first chunk
		if openFiles[record.FileID] == nil {
			targetPath := buildTargetPath(opts.OutputDir, record.Path, record.FileName)
			if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
				return fmt.Errorf("create output dir for %s: %w", targetPath, err)
			}

			handle, err := os.Create(targetPath)
			if err != nil {
				return fmt.Errorf("create output file %s: %w", targetPath, err)
			}

			openFiles[record.FileID] = &fileState{
				meta: &FileRecord{
					FileID:        record.FileID,
					FileName:      record.FileName,
					Path:          record.Path,
					FileHash:      record.FileHash,
					DateConverted: record.DateConverted,
					ModelName:     record.ModelName,
					ModelVersion:  record.ModelVersion,
					ContentType:   record.ContentType,
					SizeBytes:     record.SizeBytes,
					ChunkCount:    record.ChunkCount,
				},
				handle: handle,
				chunks: make(map[int64][]byte),
			}
		}

		state := openFiles[record.FileID]

		// Extract chunk data from appropriate column
		var chunkData []byte
		if record.ContentType == "text" {
			chunkData = []byte(record.TextData)
		} else {
			chunkData = record.BinaryData
		}

		// Just buffer for now - flush after EOF
		state.chunks[record.ChunkIndex] = chunkData

		recordCount++

		if recordCount%1000 == 0 {
			select {
			case <-ctx.Done():
				return ctx.Err()
			default:
			}
		}
	}

	// All records read - now flush all buffered chunks in order and finalize
	for fileID, state := range openFiles {
		if err := flushChunksInOrder(state); err != nil {
			return fmt.Errorf("flush chunks for file %s: %w", fileID, err)
		}
		if err := finalizeFile(state); err != nil {
			return fmt.Errorf("finalize file %s: %w", fileID, err)
		}
		state.handle.Close()
	}

	return nil
}

// flushChunksInOrder writes all buffered chunks in sequential order
func flushChunksInOrder(state *fileState) error {
	for expectedIdx := int64(0); expectedIdx < state.meta.ChunkCount; expectedIdx++ {
		data, exists := state.chunks[expectedIdx]
		if !exists {
			return fmt.Errorf("missing chunk %d for file %s (expected %d total)", expectedIdx, state.meta.FileName, state.meta.ChunkCount)
		}

		if _, err := state.handle.Write(data); err != nil {
			return err
		}

		delete(state.chunks, expectedIdx)
	}

	// Check for extra chunks
	if len(state.chunks) > 0 {
		return fmt.Errorf("extra unexpected chunks for file %s", state.meta.FileName)
	}

	return nil
}

// finalizeFile verifies all chunks were written and checks hash
func finalizeFile(state *fileState) error {
	// Check for remaining buffered chunks
	if len(state.chunks) > 0 {
		return fmt.Errorf("file %s has %d unwritten chunks - may be missing intermediate chunks", state.meta.FileName, len(state.chunks))
	}

	// Rewind and verify hash
	if _, err := state.handle.Seek(0, 0); err != nil {
		return fmt.Errorf("seek to start: %w", err)
	}

	h := sha256.New()
	if _, err := io.Copy(h, state.handle); err != nil {
		return fmt.Errorf("hash file: %w", err)
	}

	gotHash := hex.EncodeToString(h.Sum(nil))
	if gotHash != state.meta.FileHash {
		return fmt.Errorf("hash mismatch for %s: stored=%s restored=%s", state.meta.FileName, state.meta.FileHash, gotHash)
	}

	return nil
}
