package archive

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/parquet-go/parquet-go"
)

// fileState tracks a file being unpacked
type fileState struct {
	meta         *FileRecord
	handle       *os.File
	chunks       map[int64][]byte // pending out-of-order chunks, indexed by ChunkIndex
	nextChunkIdx int64            // next expected chunk index to write
}

func Unpack(ctx context.Context, opts UnpackOptions) error {
	if opts.Workers <= 0 {
		opts.Workers = 1
	}
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	return unpackCombined(ctx, opts, opts.ParquetFile)
}

func unpackCombined(ctx context.Context, opts UnpackOptions, dataPath string) error {
	f, err := os.Open(dataPath)
	if err != nil {
		return fmt.Errorf("open parquet: %w", err)
	}
	defer f.Close()

	// Safely create reader, catching panics from invalid parquet files
	var reader *parquet.Reader
	func() {
		defer func() {
			if r := recover(); r != nil {
				reader = nil // Signal invalid parquet
			}
		}()
		reader = parquet.NewReader(f)
	}()

	if reader == nil {
		return fmt.Errorf("invalid or incompatible parquet file\nThis file was not created by modelvault. Ensure you're using a parquet file generated by 'modelvault pack'")
	}

	// Track open files for direct writing
	openFiles := make(map[string]*fileState)
	defer func() {
		for _, state := range openFiles {
			if state.handle != nil {
				state.handle.Close()
			}
		}
	}()

	// Channel for decompressed, ordered records
	orderedCh := make(chan FileRecord, opts.Workers*2)
	errCh := make(chan error, 1)

	// Goroutine: Read records, decompress, and send ordered by ChunkIndex
	go func() {
		recordCount := int64(0)
		firstRecordRead := false

		for {
			var record FileRecord
			if err := reader.Read(&record); err != nil {
				if err.Error() != "EOF" {
					if !firstRecordRead {
						select {
						case errCh <- fmt.Errorf("invalid or incompatible parquet file: %w\nThis file was not created by modelvault. Ensure you're using a parquet file generated by 'modelvault pack'", err):
						default:
						}
					} else {
						select {
						case errCh <- fmt.Errorf("read record %d: %w", recordCount, err):
						default:
						}
					}
				}
				close(orderedCh)
				return
			}

			firstRecordRead = true

			// Decompress binary chunks if needed
			if record.ContentType == "binary" && len(record.BinaryData) > 0 {
				gr, err := gzip.NewReader(bytes.NewReader(record.BinaryData))
				if err != nil {
					select {
					case errCh <- fmt.Errorf("create gzip reader: %w", err):
					default:
					}
					close(orderedCh)
					return
				}
				decompressed, err := io.ReadAll(gr)
				gr.Close()
				if err != nil {
					select {
					case errCh <- fmt.Errorf("decompress binary chunk: %w", err):
					default:
					}
					close(orderedCh)
					return
				}
				record.BinaryData = decompressed
			}

			select {
			case orderedCh <- record:
			case <-ctx.Done():
				close(orderedCh)
				return
			}

			recordCount++

			if recordCount%1000 == 0 {
				select {
				case <-ctx.Done():
					close(orderedCh)
					return
				default:
				}
			}
		}
	}()

	// Main processing loop: group by FileID, order by ChunkIndex, write to disk
	for record := range orderedCh {
		// Lazy init file on first chunk
		if openFiles[record.FileID] == nil {
			targetPath := buildTargetPath(opts.OutputDir, record.Path, record.FileName)
			if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
				return fmt.Errorf("create output dir for %s: %w", targetPath, err)
			}

			handle, err := os.Create(targetPath)
			if err != nil {
				return fmt.Errorf("create output file %s: %w", targetPath, err)
			}

			openFiles[record.FileID] = &fileState{
				meta: &FileRecord{
					FileID:        record.FileID,
					FileName:      record.FileName,
					Path:          record.Path,
					FileHash:      record.FileHash,
					DateConverted: record.DateConverted,
					ModelName:     record.ModelName,
					ModelVersion:  record.ModelVersion,
					ContentType:   record.ContentType,
					SizeBytes:     record.SizeBytes,
				},
				handle:       handle,
				chunks:       make(map[int64][]byte),
				nextChunkIdx: 0,
			}
		}

		state := openFiles[record.FileID]

		// Extract chunk data from appropriate column
		var chunkData []byte
		if record.ContentType == "text" {
			chunkData = []byte(record.TextData)
		} else {
			chunkData = record.BinaryData
		}

		// Buffer chunk by index, then flush sequential chunks
		state.chunks[record.ChunkIndex] = chunkData
		flushSequentialChunks(state)
	}

	// Check for read errors
	select {
	case err := <-errCh:
		return err
	default:
	}

	// All records processed - flush any remaining buffered chunks and finalize
	for fileID, state := range openFiles {
		// Final flush of any remaining chunks
		flushSequentialChunks(state)
		if err := finalizeFile(state); err != nil {
			return fmt.Errorf("finalize file %s: %w", fileID, err)
		}
		state.handle.Close()
	}

	return nil
}

// flushSequentialChunks writes available sequential chunks in order
// Only buffers truly out-of-order chunks, keeping memory bounded
func flushSequentialChunks(state *fileState) error {
	for {
		data, exists := state.chunks[state.nextChunkIdx]
		if !exists {
			break // Stop at first missing chunk
		}

		if _, err := state.handle.Write(data); err != nil {
			return err
		}

		delete(state.chunks, state.nextChunkIdx)
		state.nextChunkIdx++
	}

	return nil
}

// finalizeFile verifies all chunks were written and checks hash
func finalizeFile(state *fileState) error {
	// All chunks should be flushed already - if not, there's a gap
	if len(state.chunks) > 0 {
		return fmt.Errorf("incomplete chunks for file (missing chunks in sequence)")
	}

	// Rewind and verify hash
	if _, err := state.handle.Seek(0, 0); err != nil {
		return fmt.Errorf("seek to start: %w", err)
	}

	h := sha256.New()
	if _, err := io.Copy(h, state.handle); err != nil {
		return fmt.Errorf("hash file: %w", err)
	}

	gotHash := hex.EncodeToString(h.Sum(nil))
	if gotHash != state.meta.FileHash {
		return fmt.Errorf("hash mismatch for %s: stored=%s restored=%s", state.meta.FileName, state.meta.FileHash, gotHash)
	}

	return nil
}
